/**
 * ESP32 secrets file
 * 
 * Contains information required to connect to WiFi and in-turn, AWS IoT
 * 
 * Authors: Vipul Deshpande, Jaime Burbano
 */


/*
  Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
  Permission is hereby granted, free of charge, to any person obtaining a copy of this
  software and associated documentation files (the "Software"), to deal in the Software
  without restriction, including without limitation the rights to use, copy, modify,
  merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
  permit persons to whom the Software is furnished to do so.
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
  INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
  PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
  HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
  OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
  SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/


#include <pgmspace.h>

#define SECRET
#define THINGNAME "ESP32"

const char WIFI_SSID[] = "Vignesh";
const char WIFI_PASSWORD[] = "qwertyuiop123";
const char AWS_IOT_ENDPOINT[] = "a3cw3ebndjpgam-ats.iot.eu-central-1.amazonaws.com";

/* Amazon Root CA 1 */
static const char AWS_CERT_CA[] PROGMEM = R"EOF(
-----BEGIN CERTIFICATE-----
MIIDQTCCAimgAwIBAgITBmyfz5m/jAo54vB4ikPmljZbyjANBgkqhkiG9w0BAQsF
ADA5MQswCQYDVQQGEwJVUzEPMA0GA1UEChMGQW1hem9uMRkwFwYDVQQDExBBbWF6
b24gUm9vdCBDQSAxMB4XDTE1MDUyNjAwMDAwMFoXDTM4MDExNzAwMDAwMFowOTEL
MAkGA1UEBhMCVVMxDzANBgNVBAoTBkFtYXpvbjEZMBcGA1UEAxMQQW1hem9uIFJv
b3QgQ0EgMTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALJ4gHHKeNXj
ca9HgFB0fW7Y14h29Jlo91ghYPl0hAEvrAIthtOgQ3pOsqTQNroBvo3bSMgHFzZM
9O6II8c+6zf1tRn4SWiw3te5djgdYZ6k/oI2peVKVuRF4fn9tBb6dNqcmzU5L/qw
IFAGbHrQgLKm+a/sRxmPUDgH3KKHOVj4utWp+UhnMJbulHheb4mjUcAwhmahRWa6
VOujw5H5SNz/0egwLX0tdHA114gk957EWW67c4cX8jJGKLhD+rcdqsq08p8kDi1L
93FcXmn/6pUCyziKrlA4b9v7LWIbxcceVOF34GfID5yHI9Y/QCB/IIDEgEw+OyQm
jgSubJrIqg0CAwEAAaNCMEAwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMC
AYYwHQYDVR0OBBYEFIQYzIU07LwMlJQuCFmcx7IQTgoIMA0GCSqGSIb3DQEBCwUA
A4IBAQCY8jdaQZChGsV2USggNiMOruYou6r4lK5IpDB/G/wkjUu0yKGX9rbxenDI
U5PMCCjjmCXPI6T53iHTfIUJrU6adTrCC2qJeHZERxhlbI1Bjjt/msv0tadQ1wUs
N+gDS63pYaACbvXy8MWy7Vu33PqUXHeeE6V/Uq2V8viTO96LXFvKWlJbYK8U90vv
o/ufQJVtMVT8QtPHRh8jrdkPSHCa2XV4cdFyQzR1bldZwgJcJmApzyMZFo6IQ6XU
5MsI+yMRQ+hDKXJioaldXgjUkK642M4UwtBV8ob2xJNDd2ZhwLnoQdeXeGADbkpy
rqXRfboQnoZsG4q5WTP468SQvvG5
-----END CERTIFICATE-----
)EOF";

/* Device Certificate */
static const char AWS_CERT_CRT[] PROGMEM = R"KEY(
-----BEGIN CERTIFICATE-----
MIIDWTCCAkGgAwIBAgIUTyOdCMIqJ3KxGcCNM1fMeJEQjp8wDQYJKoZIhvcNAQEL
BQAwTTFLMEkGA1UECwxCQW1hem9uIFdlYiBTZXJ2aWNlcyBPPUFtYXpvbi5jb20g
SW5jLiBMPVNlYXR0bGUgU1Q9V2FzaGluZ3RvbiBDPVVTMB4XDTIxMTIxOTA5NTcw
N1oXDTQ5MTIzMTIzNTk1OVowHjEcMBoGA1UEAwwTQVdTIElvVCBDZXJ0aWZpY2F0
ZTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKaNEBC0FvS5wY8bx40b
PP+MJcg/D0r9/kDB5I6KSURetTsJe2P37Bu55jyDMgypS0tiYHg/zg++Y6N6cLct
FMAgC/7szRyzfh9OVS/if1qbOX8yMI5cI/dxJlgyls5HJHZ/GHwhrN2RRnVdGXMJ
eJLvFuAj9lwnKQFl941XSmQMvXoqb6NuXVXHn5Avtk4bymZDVoAnZ7JptbCD9kNl
tc1N3dFrjrlIxLf7X1ufmkoKLgZAD8V0YzpYn81IQxKDe0tvWviTjLnz/uCbOxhM
TSlZ1JhptD0LxuAGP4lismLGH37GyBWG6t6fKlnD2e6tBCNSxVEHXT7lW9yDP2H8
QHsCAwEAAaNgMF4wHwYDVR0jBBgwFoAU6HYDWEpFjQN2bsO8Ljgs6lMkXHswHQYD
VR0OBBYEFDZmipNks+JEesi7er77ZKMSIjF/MAwGA1UdEwEB/wQCMAAwDgYDVR0P
AQH/BAQDAgeAMA0GCSqGSIb3DQEBCwUAA4IBAQBdEVTqPO/6llCQ8bIO6qXyeT72
9HgEyvGQMBPwD5So3rKDE80Y189V7SMyKR9SVjLtLgv93nSFY1xoz3XZmI3tsh6m
LQN8PoN+YBMfcjeJhkvSAvNAuBWz/SvfI/CCOP7bm+KXTzbgmpfcdw1hyqFRd5TD
wvhG0XYkBW/du2+GbpxoGqIYgZec701fnHY2rUcumOA7t2qPUO9ycqr7WZ7t0MK/
SrMi4NPR5KtlFdF7vbg7X+EDNHXe7J0yjJK9mCx+dYvvvgdCKkECLg/F6e206d/6
IAbQ4wHBuNPyyjmLEhHDuUTrAWCS4paFO43WxyVgtfRYQJrHDpkDBsyXlJmh
-----END CERTIFICATE-----
)KEY";

/* Device Private Key */
static const char AWS_CERT_PRIVATE[] PROGMEM = R"KEY(
-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEApo0QELQW9LnBjxvHjRs8/4wlyD8PSv3+QMHkjopJRF61Owl7
Y/fsG7nmPIMyDKlLS2JgeD/OD75jo3pwty0UwCAL/uzNHLN+H05VL+J/Wps5fzIw
jlwj93EmWDKWzkckdn8YfCGs3ZFGdV0Zcwl4ku8W4CP2XCcpAWX3jVdKZAy9eipv
o25dVcefkC+2ThvKZkNWgCdnsmm1sIP2Q2W1zU3d0WuOuUjEt/tfW5+aSgouBkAP
xXRjOlifzUhDEoN7S29a+JOMufP+4Js7GExNKVnUmGm0PQvG4AY/iWKyYsYffsbI
FYbq3p8qWcPZ7q0EI1LFUQddPuVb3IM/YfxAewIDAQABAoIBAQCQtAa9PHqlba7K
E6yw4HWC4dUBwigbU8pPoSZe4a7+g/qZrIdUN9cfz8hF0wbtETml6Xc/gtAZxaT0
KDE+NSDOPAmwFzWuNhTiRkClNfjIVA0EgirFxTBKkDhscKet2QnJGmu/jdKPPuUk
mxq9ZAEqSChr3VLyheOOn3URjEHJ4hD+VedTLmL3uHAGGJnXSmOtWtxjcSwyyDvt
bIyAdrpRgMosPmdLOHiiuGFnRTZbZCdssXk7jbL98g6G3ueKqSefsumKmnpT2T4G
uSX8y//hV2aBKvKgrTMSYK/PcCwtnVso7bUIQugvrD0Q/ZtJ7M2X8WsDX11SlSqE
rFMUupEhAoGBAM9dn5LDC9v/XqFssrPqSbES96GaK59y3FMMzDvVE71yCANDUU6g
jvc+xVHVFpJVtCdSjafmLsQOx2OC6jzpNzr7Z7DJzWtXi0hD/I1QTroWsI9vJJl4
tQZFgWiWXVNi2HZOoyuX63oyvJR7e9A4sNsmLti9d5IotEiA31fF04JvAoGBAM2c
5ehTzCH1shkjk09A2+w5GY9R3JBay724YQT8xg+y0n0kceNBtkdIHFXbrVCtqo45
cE501JT0+01VwznuBR1m8qwL1M0Q0XqQW8sxrDHPbEBtzMHySdK3GKgw1N7SInU9
jRh/le9fvVZqb3mpk2Nu1rAu4KCnb55ULqIZA3i1AoGADTG9147FkGf9U3QhIsWD
jtrQGt4+bFTYpAgqbpwuN12sGNkNsV0R+7VoxL40Q3dkkSP1k3tX+m2eTjykPt/v
/bbFcEBG68+UMzLwPOWhPMH41geSYpmFmzKM+2Sl54pgj5aNV1bBSvMzgJci16rj
xe32CSB1HT2tyvc4PtN9k80CgYAvSuFOuMeBICQgyB//4Kk1AkUww+F5iojGUHxw
Szu7LKRhiFpxrRGh/6IU1XxdzDQolmmQgirLQDX1Kb7HukmO47j5fZcqu62TBVU3
vWsf4dfCUf8AtRvpzZdsSB8OSUMHuGqVsfLophrEn6KYVzrBaiMTTxT3nst7nV1E
h4BW6QKBgBWppMmU50vWihG8kyTVeEhsArxaEQ2syuhalocPOkhF9IVArvfPdDAt
W2YOF8/lynUXowgU5nzviC57ZfwPAG+QsEVWmDDRAGGB11Rbl5qpFEi/2BqEIqUm
iDm84TLPu9C0grlVt7FNBojQepCpkMBGs5v1W9Vs1wryW5oF9fyf
-----END RSA PRIVATE KEY-----
)KEY";